### ISSUE TITLE
Allow time-based filter to purge & move/wormhole commands

### ISSUE THREAD

**Issue by tehhowch** [EndlessSkyCommunity/EndlessSky-Discord-Bot#111]
Because counting is hard.

**Comment by tehhowch** [comment]
Does it make sense to do both this and the messageId argument requested in #153 ?

The need for a time filter really disappears if we can use the message ID, and then also has the benefit that we don't have to worry about time zones and time deltas, at all (which is always nice)

**Comment by MCOfficer** [comment]
yeah, #153 might be a much more convenient alternative (to the programmer), while still being viable to the user.
