### ISSUE TITLE
Request for (stock) Fury data gives Doombat data instead

### ISSUE THREAD

**Issue by Bladewood** [EndlessSkyCommunity/EndlessSky-Discord-Bot#112]
![whybotmakerswhy](https://user-images.githubusercontent.com/16506683/34853246-b3cbcb6a-f700-11e7-82f1-1156fb70d806.png)

**Comment by Wrzlprnft** [comment]
i would assume it is because once james found a fury, he doesn't check wether the rest of the line is empty or so. i'll look into it

**Comment by tehhowch** [comment]
The issue is largely that James quits after a single match, rather than continuing to check for additional matches and prompting for clarification / selection.

In a different Discord bot, I've addressed this behavior with a reaction-based menu: https://github.com/AardWolf/MHTimerBot/pull/104

**Comment by MCOfficer** [comment]
![2018-07-31_14-12-06](https://user-images.githubusercontent.com/22377202/43588011-d86ac344-966b-11e8-800a-cfc6c3039dd9.gif)
I adressed in the 2.0 branch with a primitive search function (it just checks for nodes containing the query). See #36 , #22
