### ISSUE TITLE
Thumbnail template is wrong

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/EndlessSky-Discord-Bot#159]
Apparently the thumbnail template is wrong in a dozen ways and needs to be reworked.

![image](https://user-images.githubusercontent.com/22377202/78109375-564a9200-73f9-11ea-8fa8-44539b2a5809.png)

cc @beccabunny

**Comment by beccabunny** [comment]
My attemp:
[thumbnail.zip](https://github.com/EndlessSkyCommunity/EndlessSky-Discord-Bot/files/4413385/thumbnail.zip)
Game's hawk
https://raw.githubusercontent.com/endless-sky/endless-sky-high-dpi/master/images/thumbnail/hawk@2x.png
Current template hawk
![Screenshot (1538)](https://user-images.githubusercontent.com/45330165/78110028-9d855280-73fa-11ea-806d-dd6de6db485c.png)
my template hawk
![Screenshot (1537)](https://user-images.githubusercontent.com/45330165/78110048-a83fe780-73fa-11ea-9837-66bc9ed7ca16.png)
