### ISSUE TITLE
If there is no description, but there is an image, -lookup should reference GetDataType's output

### ISSUE THREAD

**Issue by tehhowch** [EndlessSkyCommunity/EndlessSky-Discord-Bot#21]
e.g. `-lookup Sol` will print the first image (the star in the system), and then the text indicating no description.

This could instead be output as the image, then "Sol is a system"

**Comment by MCOfficer** [comment]
as of fd78d8beb90079d29ffe707b392c71e91ebb331c 2.0 selects the node first and then creates a lookup embed for it (instead of trying to find a node that fits the embed).
