### ISSUE TITLE
search function for lookups

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/EndlessSky-Discord-Bot#36]
example:
input: `-search drak`
james: 
```
found the following:
1. Drak Distancer
2. Drak Archon
3. Drakon Of The Ancients
```
input: `1`
james: puts out data for distancers

**Comment by tehhowch** [comment]
Using the GitHub API may be the best approach here - let GitHub's search function do the heavy lifting
https://developer.github.com/v3/search/

then we just need to return the top 5 results via the 1 - 5 followup retrieval, and link to the search results for the rest
