### ISSUE TITLE
player timeout apparently not working

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/EndlessSky-Discord-Bot#57]
sometimes james is still in the voice channel, but not playing anything (and without any listeners).
need to investigate.

~~edit: possible caused by someone leaving james behind in paused state.~~

**Comment by tehhowch** [comment]
possible fixes:
 - assign internal DJ role to the person who started the music session
 - always stop once alone (or at least, especially if the starting listener is still online but not in the voice channel)

**Comment by tehhowch** [comment]
This happens because the player experiences a disconnect event, and successfully reconnects.
For some reason, this results in clearing the `IdleChecker` map (but not the `IdleCloser` map... :confused: ), and without any incrementing of `IdleChecker` values, `IdleCloser` does nothing.
