### ISSUE TITLE
Embedded room links are not mobile friendly

### ISSUE THREAD

**Issue by tehhowch** [EndlessSkyCommunity/EndlessSky-Discord-Bot#69]
Should be a link to off topic, but instead is the room ID
![screenshot_2017-10-04-11-55-24](https://user-images.githubusercontent.com/20871346/31188653-3d7724c6-a8fb-11e7-9ec0-579a441ddf60.png)

**Comment by MCOfficer** [comment]
i talked to the guys at the JDA discord, apparently it's a discord limitation. there's nothing we can do except sending the ID as plain text instead of using an embed.

**Comment by tehhowch** [comment]
Damn. It's a nice pretty embed on desktop. Doesn't have the same flair to
send a text message and add the reaction

**Comment by MCOfficer** [comment]
we checked with blade's iOS discord, and he can see it. so probably an android bug

**Comment by tehhowch** [comment]
I emailed a bug report to the Discord team with screenshots.

**Comment by tehhowch** [comment]
It's already on their pipeline, is an issue in Markdown apparently

**Comment by tehhowch** [comment]
[![][1]][1]

[1]: https://i.imgur.com/suU6nbU.png
